name: Deploy to cloud

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Run Tests
      run: |
        gem install bundler
        bundle exec rake test

    - name: (Service) Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.API_HOST }}
        USERNAME: root
        PORT: 22
        KEY: ${{ secrets.API_SSHKEY }}
      with:
        source: "."
        target: "/home/rails/nano_twitter_service"

    - name: (Service) Bundle and restart app server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.API_HOST }}
        USERNAME: root
        PORT: 22
        KEY: ${{ secrets.API_SSHKEY }}
        script: |
          su - rails -c "cd /home/rails/nano_twitter_service && bundle"
          sudo systemctl restart rails.service
